icons = "awesome"

[theme]
name = "solarized-dark"
[theme.overrides]
# idle_bg = "#123456"
# idle_fg = "#abcdef"
# separator = ""

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "pacman"
interval = 10

[[block]]
block = "net"
device = "wlp3s0"
ssid = true
ip = true
speed_down = true
graph_down = false
speed_up = true
graph_up = false
interval = 5

[[block]]
device = "BAT0"
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
device = "BAT1"
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{min}° min, {max}° max, {average}° avg"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %G.%m.%d %R"

